spring.application.name=TruCity

jwt.secret=0addbb55-0c2c-47b6-a894-a6d0b0694a82
jwt.expiration=86400000

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ismtusenmqwwbsawirle
spring.datasource.password=@Upper%Level!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Hikari connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=30000